/**
 * Lecture API (PRD §8 step 5; AC-9/10/11).
 *
 * Serves forward-ref-0 lectures ONE AT A TIME in topological order, per user.
 * Each lecture is generated by the gated pipeline (`generateNextLecture`), which
 * guarantees forward-reference 0 or surfaces nothing. Generated lectures are
 * persisted so resuming / re-reading is cheap, and per-user progress isolates
 * each learner's path (AC-12).
 *
 * ── Contract ──────────────────────────────────────────────────────────────
 * GET  /api/lecture?topicId=…[&userId=…]
 *      → 200 {
 *          lecture: Lecture | null,        // the CURRENT lecture to read (generated if needed)
 *          done: boolean,                  // true when the path is complete
 *          path: string[],                 // pruned topo concept ids (the sequence)
 *          completed: string[],            // concept ids already finished
 *          currentNodeId: string | null,   // concept id in front of the learner
 *          attempts?: number               // gate attempts for a freshly generated lecture
 *        }
 *
 * POST /api/lecture   (application/json), discriminated by `action`:
 *   { action:"teach",   topicId[, userId] }  → same shape as GET (ensures current exists)
 *   { action:"next",    topicId[, userId] }  → marks current complete, advances, returns the next
 *   { action:"restart", topicId[, userId] }  → clears progress, returns the first lecture
 */

import { NextResponse, type NextRequest } from "next/server";
import { getCurrentUserId } from "@/lib/auth/current-user";
import { loadGraph } from "@/lib/research/persist";
import { loadAssessmentResult } from "@/lib/assessment/persist";
import { depthProfileForLevel } from "@/lib/assessment/apply";
import type { KnowledgeGraph, Lecture, UserLevel } from "@/lib/ontology/types";
import { generateNextLecture } from "@/lib/lectures";
import { buildLearningPath, nextConceptId } from "@/lib/lectures/path";
import {
  advanceProgress,
  loadLecture,
  loadProgress,
  saveLecture,
  saveProgress,
  type Progress,
} from "@/lib/lectures/persist";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** A learner with no assessment yet defaults to a beginner profile. */
function defaultLevel(): UserLevel {
  return {
    level: "beginner",
    knownConceptIds: [],
    depthProfile: depthProfileForLevel("beginner"),
  };
}

async function resolveLevel(
  userId: string,
  topicId: string,
): Promise<UserLevel> {
  return (await loadAssessmentResult(userId, topicId)) ?? defaultLevel();
}

type LectureResponse = {
  lecture: Lecture | null;
  done: boolean;
  path: string[];
  completed: string[];
  currentNodeId: string | null;
  attempts?: number;
};

/**
 * Ensure a lecture exists for the learner's CURRENT concept (generate + persist
 * if missing), and return the full response shape.
 */
async function serveCurrent(
  userId: string,
  topicId: string,
  graph: KnowledgeGraph,
  level: UserLevel,
): Promise<LectureResponse> {
  const path = buildLearningPath(graph);
  const progress = await loadProgress(userId, topicId);
  const completed = progress.completedConceptKeys;

  // The concept the learner is on = explicit current, else the next un-taught.
  let current = progress.currentNodeId ?? nextConceptId(graph, completed);

  // Guard: a stale/known current that is no longer in the path → recompute.
  if (current && !path.includes(current)) {
    current = nextConceptId(graph, completed);
  }

  if (!current) {
    if (progress.currentNodeId !== null) {
      await saveProgress(userId, topicId, {
        completedConceptKeys: completed,
        currentNodeId: null,
      });
    }
    return { lecture: null, done: true, path, completed, currentNodeId: null };
  }

  // Persist current pointer if it wasn't set yet.
  if (progress.currentNodeId !== current) {
    await saveProgress(userId, topicId, {
      completedConceptKeys: completed,
      currentNodeId: current,
    });
  }

  // Cheap resume: return a previously generated lecture if present.
  const existing = await loadLecture(topicId, current);
  if (existing) {
    return { lecture: existing, done: false, path, completed, currentNodeId: current };
  }

  // Generate the next (== current) lecture, gated to forward-reference 0.
  const result = await generateNextLecture(graph, level, completed);
  if (!result.lecture) {
    return { lecture: null, done: true, path, completed, currentNodeId: null };
  }
  await saveLecture(topicId, result.lecture);
  return {
    lecture: result.lecture,
    done: false,
    path,
    completed,
    currentNodeId: result.lecture.conceptId,
    attempts: result.attempts,
  };
}

/**
 * Advance: mark the current concept complete, move to the next one, generate +
 * persist its lecture, and return it.
 */
async function serveNext(
  userId: string,
  topicId: string,
  graph: KnowledgeGraph,
  level: UserLevel,
): Promise<LectureResponse> {
  const path = buildLearningPath(graph);
  const progress = await loadProgress(userId, topicId);
  const justCompleted =
    progress.currentNodeId ?? nextConceptId(graph, progress.completedConceptKeys);

  const taughtAfter = new Set(progress.completedConceptKeys);
  if (justCompleted) taughtAfter.add(justCompleted);
  const taught = [...taughtAfter];

  const next = nextConceptId(graph, taught);
  const advanced: Progress = await advanceProgress(
    userId,
    topicId,
    justCompleted,
    next,
  );

  if (!next) {
    return {
      lecture: null,
      done: true,
      path,
      completed: advanced.completedConceptKeys,
      currentNodeId: null,
    };
  }

  const existing = await loadLecture(topicId, next);
  if (existing) {
    return {
      lecture: existing,
      done: false,
      path,
      completed: advanced.completedConceptKeys,
      currentNodeId: next,
    };
  }

  const result = await generateNextLecture(graph, level, taught);
  if (!result.lecture) {
    return {
      lecture: null,
      done: true,
      path,
      completed: advanced.completedConceptKeys,
      currentNodeId: null,
    };
  }
  await saveLecture(topicId, result.lecture);
  return {
    lecture: result.lecture,
    done: false,
    path,
    completed: advanced.completedConceptKeys,
    currentNodeId: result.lecture.conceptId,
    attempts: result.attempts,
  };
}

async function loadServeContext(topicId: string) {
  const graph = await loadGraph(topicId);
  if (!graph) return { error: "unknown topicId", status: 404 as const };
  if (graph.nodes.length === 0) {
    return {
      error: "graph has no concepts yet; wait for research to produce nodes",
      status: 409 as const,
    };
  }
  return { graph };
}

export async function GET(request: NextRequest) {
  const topicId = request.nextUrl.searchParams.get("topicId") ?? "";
  if (!topicId) {
    return NextResponse.json({ error: "`topicId` is required" }, { status: 400 });
  }
  const ctx = await loadServeContext(topicId);
  if ("error" in ctx) {
    return NextResponse.json({ error: ctx.error }, { status: ctx.status });
  }
  const userId = await getCurrentUserId(
    request.nextUrl.searchParams.get("userId") ?? undefined,
  );
  const level = await resolveLevel(userId, topicId);
  try {
    const body = await serveCurrent(userId, topicId, ctx.graph, level);
    return NextResponse.json(body);
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "lecture error" },
      { status: 500 },
    );
  }
}

type Body = {
  action?: "teach" | "next" | "restart";
  topicId?: string;
  userId?: string;
};

export async function POST(request: NextRequest) {
  let body: Body;
  try {
    body = (await request.json()) as Body;
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }

  const topicId = (body.topicId ?? "").trim();
  if (!topicId) {
    return NextResponse.json({ error: "`topicId` is required" }, { status: 400 });
  }

  const ctx = await loadServeContext(topicId);
  if ("error" in ctx) {
    return NextResponse.json({ error: ctx.error }, { status: ctx.status });
  }

  const userId = await getCurrentUserId(body.userId);
  const level = await resolveLevel(userId, topicId);

  try {
    switch (body.action) {
      case "next": {
        const res = await serveNext(userId, topicId, ctx.graph, level);
        return NextResponse.json(res);
      }
      case "restart": {
        await saveProgress(userId, topicId, {
          completedConceptKeys: [],
          currentNodeId: null,
        });
        const res = await serveCurrent(userId, topicId, ctx.graph, level);
        return NextResponse.json(res);
      }
      case "teach":
      case undefined: {
        const res = await serveCurrent(userId, topicId, ctx.graph, level);
        return NextResponse.json(res);
      }
      default:
        return NextResponse.json(
          { error: "`action` must be one of: teach, next, restart" },
          { status: 400 },
        );
    }
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "lecture error" },
      { status: 500 },
    );
  }
}
